[build-system]
requires = ["maturin>=1.9.4,<2"]
build-backend = "maturin"

[project]
name = "scan-py"
version = "0.2.1"
description = "Python package for SCAN change-point detection"
readme = "README.md"
license = "GPL-3.0-only"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.23",
    "pandas>=1.5",
    "plotnine>=0.12",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Mathematics",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
]


[project.optional-dependencies]
test = [
    "pytest>=8",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[project.urls]
Homepage = "https://github.com/Prabashoka/scan-py"
Repository = "https://github.com/Prabashoka/scan-py"
Issues = "https://github.com/Prabashoka/scan-py/issues"

[tool.maturin]
python-source = "python"
module-name = "scan._scan_rust"
features = ["pyo3/extension-module"]
